- name: add ansible-pull cron job
  cron:
    name: "ansible auto-provision"
    user: "ansible"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Ismail0817/ansible_pull.git"
